namespace RO.DevTest.Domain.Common.Models;

/// <summary>
/// Represents the revenue generated by a specific product within a sales analysis period.
/// This model resides in the Domain layer.
/// </summary>
public class ProductRevenueResult
{
    public Guid ProductId { get; set; }
    public string ProductName { get; set; } = string.Empty;
    public decimal TotalRevenue { get; set; }
}

